const QUOTES = [
    // 2021-2022
    "\"I feel like rum-soaked gummy bears gives me sweatpants and Viagra vibes.\"",
    "\"Adele could be complicit in war crimes.\"",
    "\"Nelson Mandela is at work here.\"",
    "\"I'll ask my mom to email me my Nerf guns.\"",
    "\"Would you rather be the size of a lake but extremely wise, a bird the size of a human but you retain your current level of wisdom, or have a powerful trunk and be slightly wiser?\"",
    "\"The moral of the story is: don't eat before drinking.\"",
    "\"I was a child sexist.\"",
    "\"As a child, she was a MILF - relative to children.\"",
    "\"Consider this: snakes move. But how do they move?\"",
    "\"I should up my drug game: I'm lacking.\"",
    "\"Apparently I said, 'I've seen the face of God, and it's not pretty.'\"",
    "\"I prefer cars that go outdoors though.\"",
    "\"We need to find the WD40 of WD40s.\"",
    "\"I see myself in third person when it rains.\"",
    "\"Are you playing the long game, or are you playing the losing game?\"",
    "\"Can I say something bitchy? I thought you guys would be better at this.\"",
    "\"You're expecting to get off, and then everybody dies.\"",
    "\"God should have left that in the drafts.\"",
    "\"I'm like porn for librarians in a hireable sense.\"",
    "\"They probably think I'm some tweaker-ass bitch who has no concept of life itself.\"",
    "\"I horned up midway through ninth grade.\"",
    "\"I like hills more than stairs in a philosophical sense.\"",
    "\"It's like: let's all jerk off together.\"",
    "\"It's like the quarantine version of hate-fucking.\"",
    "\"When are we doing the nasty?\"",
    "\"You don't mix your chicken is what I'm saying.\"",
    "\"I don't practice being Polish.\"",
    "\"I lowkey think I've inhaled glue.\"",
    "\"It's like cyberbullying but in real life.\"",
    "\"A hoe doesn't get cold.\"",
    "\"Ask not what you should do for the male gaze; Ask what the male gaze can do for you ... It's like reparations.\"",
    "\"Tomorrow will be a better day ... Well, it'll be a better day for me; I don't know about you.\"",
    "\"I'm really scared there's a banana in my room that I don't know about.\"",
    "\"You should die just to fuck with him.\"",
    "\"I'm a cutie, but he likes me because he thinks I'm a dumb donkey.\"",
    "\"Everyone knows I look like a fugly marshmallow during winter.\"",
    "\"I can't put 'pemis' on the crotch area.\"",
    "\"Only little nerds drool.\"",
    "\"In that moment, I understood what it meant to be a pemis.\"",
    "\"Does Jesus lay the eggs?\"",
    "\"I do not endorse these delusions.\"",
    "\"I think I'm a social power bottom.\"",
    "\"I'm the orange juice gas man.\"",
    "\"Wait, why is bestiality wrong?\"",
    "\"I was busy seducing those Cheez-Its.\"",
    "\"I'm a bitch for fresh fruit.\"",
    "\"I'm more likely to break than dance.\"",
    "\"Wait, who are we bullying?\"",
    "\"I'll quarter your mom's head.\"",
    "\"My style is just yeeting all over the place.\"",
    "\"Yep, she has big titteronis.\"",
    "\"I am secretly COVID.\"",
    "\"Tasteful sluttiness: it's hard to do.\"",
    "\"This is gonna sound weird, but you have really cute toes.\"",
    "\"I have sucked on a lot of toes.\"",
    "\"I'm gonna do it - no regard for human life.\"",
    "\"The Earth's rotation around the sun is a viscous [sic] cycle.\"",
    "\"I hope people describe me as a drunk.\"",
    "\"You uterus-less fool!\"",


    // 2022-2023
    "\"Deep and complex; it makes the meat taste meatier.\"",
    "\"My therapist calls them the sad boys club.\"",
    "\"Hot bananas are good.\"",
    "\"If we smother someone to death with a pillow, is that juice?\"\n\"Yeah.\"",
    "\"I think emotions are significantly harder than being horny.\"",
    "\"Going back to feminist oppression, gender is juice.\"",
    "\"That's a really sexy horse.\"",
    "\"You look like the pope if the pope was an incel.\"",
    "\"I've fallen into the Panama Canal and I can't get out.\"",
    "\"What's wrong with Canada? IT'S TRYING TO KILL YOU.\"",
    "\"The B in BLT stands for Canadian moose.\"",
    "\"Have you ever heard of Jesus? That ice cream had some fucking Jesus in it.\"",
    "\"Jesus Christ? More like Jesus my testicles.\"",
    "\"Everyone turn around.\"\n\"No.\"\n\"Then I cannot show you God.\"",
    "Beast reciting the Pledge of Allegiance: \"One nation, one and only.\"",
    "\"My fifth grade teacher is basically the nucleation site of my memories.\"",
    "\"If you think about it, elementary school is like P/NR.\"",
    "Beast discussing Brass Rats: \"It's just a silly little capitalism thing.\"",
    "Beast discussing an anonymous person washing dishes on hall: \"This feels like the communal kitchen version of, 'I can change him'.\"",
    "\"I've been meowing since Sonic.\"",
    "\"Are you okay? You're not making 'your mom' jokes any more.\"",
    "\"What do you think FFT stands for? Free Food Tapeworm!\"",
    "\"It's so pretty and sad. I'm into that.\"",
    "Beast discussing The (Leaky) Sink: \"'It works as long as I'm holding there' is like 'should I stay in a toxic relationship.'\"",
    "\"I feel like 'hosed' is a very MIT-local phrase: no one says that at Harvard.\"\n\"Getting an education at Harvard is not like drinking out of a firehose.\"\n\"It's just drinking.\"",
    "Beast discussing Beast: \"We're more than just a frat: we're family.\"",
    "\"Turn off the fish or whatever.\"",
    "\"They go in and out of being gay with ease.\"",
    "\"You can put the bodies in my room.\"",
    "\"I'm mentally stable, but not stable at a good point.\"",
    "\"One man's Brash is another man's  Breasure.\"",
    "\"If you see a tall person, remember to remind them that they are tall and ask them how the weather is up there.\"",
    "\"Coding is a pyramid scheme.\"",
    "\"Don't stay inside for too long, kids: you'll learn Haskell!\"",
    "\"So I'm the bad guy for giving space to cats and letting them give me fish.\"",
    "\"I don't speak: I just talk.\"",
    "\"I feel like Buzzfeed speaks the universal human experience.\"",
    "\"I'm Brothing at the mouth for your Brother.\"",
    "\"I don't feel weird about your ears.\"",
    "\"Does anyone want the ground ... strawberry?\"",
    "\"Eight is a great number: it's twice as round as zero!\"",
    "\"I'm depressed but it's okay: CORGI\"",
    "\"It's like corn: it has layers.\"",
    "Beast discussing rooibos tea: \"ROYGBV-TEA\"",
    "Beast discussing the Kingkiller Chronicle:\n\"Huh, why do we have such different memories of this book?\"\n\"Maybe because I read this book in high school, and I'm not obsessed with women.\"",
    "\"Guys! We made 2^1 cookies.\"",
    "Beast discussing Nertz:\n\"It's not an addiction: it's an obsession.\"\n\"It's a lifestyle.\"",
    "Beast discussing the LD50 of Nertz: \"We're gonna play Nertz until half of us die.\"\nLater: \"With the LD50 thing, I'm okay with you guys saying it at my funeral.\"",
    "\"It's not just rats: people die, too.\"",
    "\"Your mother is the queen of spades.\"",
    "\"'Do you like tasty?' Was that a threat?!\"",
    "\"Sometimes I forget I'm not a car.\"",
    "\"Does it have to be true? No, it just has to be in Spanish.\"",
    "\"Why walk when you can go in an ambulance?\"",
    "\"Why get AdBlock when you could get laundry that stays fresh for weeks?\"",
    "\"The L in love stands for lung cancer.\"",
    "\"There's a woman and a fossil and they're in love.\"",
    "\"Step one: admitting you're an arsonist.\"",
    "\"Shaking SMHing my head\"",
    "\"You don't have to murder your husband: it's just a vibe if you do.\"",
    "\"Hexagons are the bestagons.\"",
    "\"Look, it's a burger.\"\n\"Me too.\"",
    "\"You get to date the general concept of the brainstem.\"",
    "\"Wait, you shouldn't eat knives?\"",
    "\"Tears get in the way of Nertz.\"",
    "\"The real crime was the friends we made along the way.\"",
    "\"The subset of people I care about is the singleton of your mom.\"",
    "\"I meant go fast: don't flash it!\"",
    "\"I'm just like the other girls: I like Nertz.\"",
    "\"Save a train; ride a cowboy.\"",
    "\"I really want textured vegetable protein in my life.\"",
    "\"My calves and thighs are unmatched in all mankind.\"",
    "\"This philosophy class has bitchified me.\"",
    "\"I love my sister, but Girl Scout cookies is where I draw the line.\"",
    "\"I think I am a nitwit.\"",
    "\"I'm sure you'd make a great ecoterrorist.\"",
    "\"We can make the pancakes blue because that's where we put our sadness.\"",
    "\"Spend all your time thinking of the quasicoherent sheafussy.\"",
    "\"Blood tastes nicer.\"",
    "\"Think horizontal thoughts.\"\n\"You should've said, 'Think squiggly thoughts'!\"",
    "\"Water is our biggest export here.\"\n\"Water and Nertz.\"",
    "\"What the opposite of slay ... like, revived?\"",
    "Beast discussing Black Swan: \"Yassified whiplash\"",
    "\"It's so pretty! it's like we're cute little women in France.\"",
    "\"Cereal is an iterative process.\"\nLater, relatedly: \"Beast is full of haters.\"",
    "\"It's bisexual o'clock, guys!\"",
    "\"Submissive and breedable versus oppressive and ... sterile?\"",
    "\"I consider myself a libertarian centralist. I don't know what those mean: they're just bad words.\"",
    "\"I'm a multimorphic ... pussypoppinslayqueen.\"",
    "\"I'm tired. Stab me.\"",
    "\"It's not about getting stabbed, it's about what getting stabbed can do for you.\"",
    "\"Nice yawn.\"\n\"Thanks, I did it myself.\"",
    "\"I'm a half-capacity teeth.\"",
    "Beast backronyming SLAY: \"small LED array yass\"",
    "\"You either die a foot-lover or live long enough to see yourself become foot-loving.\"",
    "\"It does not in fact taste like childhood: it tastes like corn.\"",
    "\"I'm not strong enough to grow apples either.\"",
    "\"What bodily fluid is that?\"\n\"Gatorade.\"",
    "\"Brain? There. (I checked.)\"",
    "\"Banana, wine, and green: the three genders.\"",
    "\"When my happiness disappears, I produce milk tea.\"",
    "Beast discussing twins: \"Triplets but a double.\"",
    "\"Life is fake.\"\n\"But Nertz is real.\"",
    "\"You're like me playing Nertz, but in real life.\"",
    "Beast discussing the math department Pi Day celebration:\n\"They bought 2 pies for 100 people.\"\n\"#math.\"",
    "\"I played 3 hours of Nertz today.\"\n\"No, you've played\" (checks watch) \"4 minutes of Nertz today.\"",
    "*sniff sniff* \"Smells like an omega right there.\"",
    "\"That was an unsatisfying game of Nertz. It was too long. We should play again.\"",
    "\"SO TRUE GIRLFRIENDS KILL.\"",
    "\"You're telling me you never had to slay anyone in Germany?\"",
    "\"It's like really bestie die.\"",
    "\"Me when the laugh is metronomic and the sneeze has character.\"",
    "Beast discussing writing stories: \"I'm channeling specific flavors of hrrginess in each of my characters.\"",
    "Beast discussing the MBTA: \"The T is for Bertucci's.\"",
    "\"I wasn't there, but I did hear you talking about her with great lust.\"",
    "\"We should watch Pirates *Against* the Carribean next.\"",
    "\"I feel like [dying] would be good for your health because if you die, you can't get sick.\"",
    "\"It's like a video game speed-slow-down effect in real life.\"\n\"It's almost like physics exists in real life.\"\n\"Oh my god ... you're actually right.\"",
    "\"You know what would be even more slay and independent of you? Playing the two of diamonds.\"",
    "Beast discussing playing the four of spades: \"I'm adding liquid assets to the market.\"",
    "\"Always playing cards in the middle is a good first-order approximation.\"",
    "\"When you play Nertz, you lose the ability to count past 13.\"",
    "Beast discussing drink carbonation:\n\"It's angry.\"\n\"It's bloodletting.\"",
    "\"I forgot the mu naught like a person who makes mistakes but is not an idiot.\"",
    "\"Babe wake up it's time to sleep.\"",
    "\"Let's cap it at the furry shit.\"",
    "\"It's on the posters.\"\n\"Oh I don't use my eyes.\"",
    "\"I think the hot dog is RP^infinity.\"",
    "Beast discussing stand mixers:\n\"I heard those are really expensive.\"\n\"Yeah ... if you're broke!\"",
    "\"The orthodontist's carnival was a lot of fun! Unfortunately, I don't have teeth any more.\"",
    "Beast discussing Ben and Jerry's:\n\"When a bengineer and a jengineer love each other very much ...\"\nLater: \"When a meese and a meese love each other very much ...\"",
    "\"Do you desire to desecrate your ceremonial-grade matcha crepes with fluff?\"",
    "\"Memories go away, but big plastic cubes last forever -- and memories of big plastic cubes last even longer!\"",
    "\"You know, personally, I think you should git push him down the stairs.\"",
    "\"The first rule of whale ownership: don't rip their eyes out!\"",
    "\"It's like 69 but for hands.\"",
    "\"Feet are of an emotionally neutral expression.\"",
    "\"What would make this room spectacular? Suicidal dolphins.\"",
    "\"Your lesbian inflated cow fetish doesn't hurt anyone ... I think.\"",
    "\"Bitchin' in the kitchen.\"\n\"Bitchin' in the bitchen!\"",
    "\"Wait, let me get this straight: you have a crush on the upper half of his face?\"",
    "\"Self-inducting third nipples\"",
    "\"You mean big beaver deltoids?\"",
    "\"Sometimes I grow balls, usually by the end of the semester.\"\n\"Balls come and go over the course of a semester.\"",
    "\"I'm gonna go press-fit my child.\"",
    "\"Does it taste like the Industrial Revolution or something?\"",
    "\"Hang on, I gotta fix the analysussy.\"",
    "\"Does anyone have a girlfriend or is a girlfriend?\"",
    "\"You make one life-changing choice and suddenly you have to carry a box.\"",
    "\"It's an honor to be your emotional support army.\"",
    "\"Where there's a Beast, there's a fuck.\"",
    "\"More often than not, the victim deserves to be blamed. It's a skill issue on their part.\"",
    "\"The line between gay and Karen is very fine.\"",
    "\"I think you shouldn't ride a horse here anyways: you'd get decapitated.\"",
    "\"The eggs are ambidextrous?\"",


    // 2023-2024
    "\"It's like self-deprecating, but deprecating other people!\"",
    "\"I'm like a big pea fan.\"",
    "\"Don't you know there's a straight person in every shredder?\"",
    "\"I wear shirts and pants and underwear and also crocs and sometimes socks.\"",
    "\"When I see your mom and move left and right, I see hearts.\"",
    "\"I'm pro-ussy ... prussy?\"",
    "\"Let's take the dorms estrogen picking.\"",
    "\"I need to date a birational geometer.\"",
    "\"You have a nice thing like every month.\"\n\"Like a period?\"",
    "\"Aren't opossums, like, monkeys?\"",
    "\"I'm the coldest motherfucker alive!\"\n\"Do you need a jacket?\"",
    "\"Why are you waiting for ...\"\n\"Marriage?\"\n\"For the economy to crash.\"",
    "\"This guy gets off thinking about the Aurora (the Russian ship).\"\n\"You get off thinking about dual citizenship.\"",
    "\"I was your mother.\"",
    "\"DMs don't mean anything; I want a MILF.\"",
    "\"You will finish two whole pizzas, but you will never finish a MILF.\"",
    "\"I should've gone raining.\"",
    "\"What do rich people do if they get seasick easily?\"",
    "\"You're just obsessed with his babygirl waist.\"",
    "\"If you ever need to talk about women, I would love to listen.\"",
    "\"My tastes for Asians skews DILFs.\"",
    "\"Being gay is bad.\"\n\"That's, like, homophobic.\"",
    "\"Sorry, please remove your boobs: that's cheating.\"\n\"You've become too mommy.\"",
    "\"She's a MILDEW: a mother I'd like to discuss economics with.\"",
    "\"He's, like, the perfect model of what you want in a woman.\"",
    "\"The weather outside is frightful, but the scallion pancakes are quite delightful!\"",
    "\"I also don't know what I'm doing with my life.\"\n\"But you have a lot of red flags.\"",
    "\"6-3s do good things for the world ... sometimes ... on some occasions ... when they feel like it.\"",
    "\"Not to ruin the mood, but this is exactly where you'd get ax-murdered in a Criminal Minds episode.\"",
    "\"Making mistakes is a full-time occupation.\"",
    "\"He's like babygirl uncle vibes.\"",
    "\"I think I need to learn how to regulate my mouth.\"",
    "\"We collectively generate one cup of happiness between all of us.\"",
    "\"I'm gonna go eat ice cream and cry. Actually, maybe I won't cry: I'm too lazy.\"",
    "\"Illegal adultness? That's called being a minor.\"",
    "\"We should leverage the racism against the homophobia.\"",
    "\"You are a bag of protein; shut the fuck up.\"",
    "\"Some train tracks are so remote that trains can't get to them.\"",
    "\"I'm being objectified not in the sexual way but in the cannibalistic way, so it's acceptable.\"",
    "\"If I was not involved in the incest and was trying to uncover the incest, that could be fun.\"",
    "\"Well, your wife might be gone, but you can always marry a round American woman.\"\n\"In MONTANA.\"",
    "\"He was penetrated multiple times and didn't die.\"\n\"Bottom energy.\"",
    "\"You should robotically manipulate him on your lap.\"\n\"You should normally manipulate him.\"",
    "\"You should use the word 'ubiquitization' in your paper at least once.\"",
    "\"Sometimes, you gotta be down bad in order to be up good.\"",
    "\"I have a mommy radar.\"",
    "\"Opioids work.\"",
    "\"It's like doing one piece of drugs.\"",
    "\"You need to find your intellectual masturbatory aide.\"",
    "\"I am the most ethical person to have ever ... ethicked.\"",
    "\"Okay, fine, by technicality, you're a human, I guess.\"",
    "\"I chose violence, every day, all the time.\"",
    "\"Growing up itself is a mistake.\"",
    "\"It's an intro class like getting shot is an intro to pain.\"",
    "\"We could kill people, and we did kill people. It was fun.\"",
    "\"I thought dumb thotticus was the name of a drink.\"",
    "\"It's not a character flaw, just a personality flaw.\"",
    "\"I've never worked with numbers as a math major.\"",
    "\"Sigma males just sit in their rooms and ... edge or something.\"",
    "\"They can wet themselves.\"",
    "\"We did not wash our hands with truffle seasoning.\"",
    "\"Wait no, you're not good. You're sorry.\"",
    "\"The haunting children would be, like, a hobby.\"",
    "\"All finite sets have size one.\"",
    "\"Focus on the pee, and then get the D working.\"",
    "\"If you think about it, a missile is like a human-sized stripper pole laid on its side.\"",
    "\"They're nice people! They make 'your mom' jokes!\"",
    "\"I have a feeling that pie is not the best way to get drunk.\"",
    "\"If someone likes my Hinge profile, it's a red flag: it means they have bad taste.\"",
    "\"How did I ask you to find something mathematical and you find anime?\"",
    "\"Some people are sexy blobs.\"",
    "\"I like tenderizing.\"",
    "\"How do you sexually break someone's back?\"\n\"With rizz.\"",
    "\"They don't call me Footcasso for nothing.\"",
    "\"She has a high tolerance for bullshit but a low tolerance for cringe.\"",
    "\"So you look at a fruit and just see a number?\"\n\"Yeah, bell pepper is 4688.\"",
    "\"Maybe they have a strong attachment to the milk.\"\n\"Maybe they made it themselves.\"",
    "\"When you search up 'heroin', surprise surprise: it's all heroin!\"",
    "\"If you drink the heroin, I'm covering your tab.\"",
    "\"Don't shoot newborns/toddlers with Nerf guns.\"",
    "\"I was very young for my age.\"",
    "\"Is gin good straight?\"\n\"Who?\"",
    "\"You should get the immortal snail to mine cryptocurrency.\"",
    "\"Is this Python rehabilitation?\"",
    "\"Schroedinger's tofu bread.\"",
    "\"It's not his birthday. We can make him choke.\"",
    "\"Would you want me as your emotionally stable elder brother?\"",
    "\"You know, a bee being violent is basically like a bee twerking.\"",
    "\"I wish there are sexier chairs.\"",
    "\"You seem to be a person who knows about drug things.\"",
    "\"I'm a gender absurdist.\"\n\"And I'm a denialist.\"",
    "\"Please stab me through the hole.\"",
    "\"Do you want tomato juice? You should drink a lot of tomato juice. Oh god my stomach hurts.\"",
    "\"His specs (as a PC) are my type, but I don't know if his emotional performance is enough for the games I want to play.\"",
    "\"MacGregor is gregging.\"",
    "\"Call me the MBTA because I break down frequently.\"",
    "\"How was work?\"\n\"Good, I make large language models yap.\"",
    "\"I could extract ... some meaning.\"",
    "Beast discussing tech bros:\n\"Is there a word like techgirl?\"\n\"Mommy?\"",
    "\"Friendship ended with twink aesthetic; now yacht club MILFie aesthetic is my BFF.\"",
    "\"I would like you to know the idea of giving someone else part of my paycheck was so terrifying, it woke me up from almost falling asleep \\hj\"",
    "\"The emotional foreplay of therapy hadn't even started yet and she's already gone.\"",
    "\"Scooter girl summer won't scoot itself.\"",
    "\"And then I say, 'Screw you\ — I don't say that I'm meaner.\"",
    "\"Screwdriver is like a helpful stick basically.\"",
    "\"I think she is pretty Sanrio-agnostic.\"",
    "\"I don't think I see any that are just 'the fuck.'\"",
    "\"Do class years of indeterminate genders count?\"",
    "\"You're not cute: you're a badass hottie baddie bitch.\"",
    "\"Stick it in harder.\"",
    "\"Still a pedantic asshole, just smaller packaging.\"",


    // 2024-2025
    "\"Convenience is the thing to strive for and any safety benefits are purely coincidental.\"",
    "\"We play with very different sets of balls.\"",
    "\"Mommy knows best.\"",
    "\"There's a lot of pride in elephant cock.\"",
    "Beast discussing a shot of mac and cheese: \"My tongue is too short for this.\"",
    "\"I'm so sorry, you're so right! Okay, um. Perish.\"",
    "\"The stork descends, performs a C-section, then leaves.\"",
    "\"You are not allowed to be gay until you get better cabinets.\"",
    "\"Not old, not young, but a viable dieable age.\"",
    "\"Damn. You have skin.\"",
    "\"Are Mass-holes just tsunderes?\"",
    "\"I'm not crazy, just cringe.\"",
    "\"Let's see what the moans are.\"",
    "\"Actually, I think God left Twitter.\"",
    "\"GIVE ME THE FUCKING POWDER!\"",
    "\"Why is there code in your centrifuge?\"",
    "\"I sound like a crack addict.\"",
    "\"What? You don't like ethnic cleansing?!\"",
    "\"I'm not looking up fish porn.\"",
    "\"Is my ass fooded at all?\"",
    "\"Each black card counts as 3/5 of a white card.\"",
    "\"Is god not homophobic now?\"\n\"Maybe I'm straight now.\"",
    "\"EC bathrooms are essentially the Sistine Chapel.\"\n\"I thought EC had a lower than average number of cis teens.\"",
    "\"It's kind of weird talking to people without read receipts.\"",
    "\"Love is temporary; mahjong is forever.\"",
    "\"If your brain was a tooth, it would need so much dental filling.\"",
    "\"What's a word that starts with H?! Oh, whore.\"",
    "\"I think I could fuck that forklift.\"",
    "\"Have you just been giving people chlamydia?!\"",
    "\"People are making babies, but they're getting eaten.\"",
    "\"I'm gonna burn the penis!\"",
    "\"Cwunchy? Why are the boobs cwunchy?\"",
    "\"You might as well be turned into a soup.\"",
    "\"You can come rotate my shapes.\"",
    "\"What did you get? Sexy egg and cheese sandwich?\"",
    "\"I could touch your junk but it's okay.\"",
    "\"Writing is easy; trimming down to word limit is hard.\"\n\"This is why you go to Harvard and I go to MIT.\"",
    "\"Have you considered unfucking?\"",
    "\"I will shit your pants.\"",
    "\"Can I sit on something hard? By that I mean something soft.\"",
    "\"People should just get better at beating each other up. It's cheaper when you're better at it.\"",
    "Beast discussing bowling: \"Beast Only Wants a Lawyer.\"",
    "\"The plural of toast?\"\n\"Teese.\"",
    "\"This toast is not just well-done: it's congratulations.\"",
    "\"What if grandpa is promiscuous?\"",
    "\"If I was a graham gracker...\"\n\"I'd be scared.\"",
    "\"It's like fuck around and find out but in a cottagecore way.\"\n\"Cottagecore with a uranium block.\"",
    "\"Cough your lungs out already: you'll save me a problem.\"",
    "\"Psets aren't on birth control.\"",
    "\"Her skin is still here though.\"",
    "\"I was cleaving meat, then I was cleaving me.\"",
    "\"Oh, there's a second penis. Huge. It's also a lot more obvious, too.\"",
    "\"Of course you have dyed hair pronouns.\"",
    "\"There's no tops in this room.\"",
    "\"If I had a completely different personality, I would make such a good Discord kitten.\"",
    "\"You touch grass, by which I mean you touch an algebraic variety.\"",
    "\"I know you're not concussed 'cause you're being fucking annoying!\"",
    "\"You did 9/11?!.\"\n\"Yeah, but you can't tell anyone.\"",
    "\"I am the Christ.\"",
    "\"I'm pregaming the hentai event. Don't worry about it.\"",
    "\"That foot's doing weird things.\"\n\"You would to if you had 8 frames.\"",
    "\"Grooming 2: Electric Boogaloo.\"",
    "\"No cave can accommodate three snakes!\"",
    "\"I can't just back into the shaft.\"",
    "\"It's okay if I look through your feed because I won't judge you for any furry porn that's in it.\"",
    "\"I hope that every time you get threatened in the future, you think of me.\"",
    "\"More ass? Yeeeaaahh.\"",
    "\"I just have to survive till Friday.\"\n\"It'd be nice if you didn't have to.\"",
    "\"Do you know what else is a weird thing to say? Chlamydia.\"",
    "\"I was told I should not meow because they don't like autistic people....\"",
    "\"Well, it's a furry meme—not about touching toes.\"",
    "\"I'm sorry this looks entirely inbred to me.\"",
    "\"I feel like catboys have very little strategic value.\"",

    // 2025-2026
    "\"Do you need pads? They're on sale.\"\n\"What kind of pads?\"",
    "\"Can you feel his kidney stone?\"",
    "\"I was gonna sign us up for Pornhub, but it was already in use.\"",
    "\"All the objects in my life are male.\"",
    "\"I capitalize my numbers.\"",
    "\"I think 2 is the hottest number because you can write it in so many different ways.\"",
    "\"Why does no one trust me with a knife?\"",
    "\"Do you wanna be less gay? We can make you less gay.\"",
    "\"My earliest conscious memory was eating a McChicken.\"",
    "\"Hyperfocus on your own dick.\"",
    "\"Why are you touching Snorlax like that?\"",
    "\"I am a necrophiliac.\"",
    "\"Guys, check out my new fidget toy—OUCH!\"",
    "\"I was about to say, I don't eat twinks.\"",
    "\"Don't remind me his name, who's the guy that killed JFK ... Harriet Tubman.\"",

    // Template for easier copy-pasting
    // "\".\"",

    // Note: newlines (\n) don't work with jQuery, but we might want to keep
    // them anyway in case we change to another implementation in the future.
];

Object.freeze(QUOTES);
